### ISSUE TITLE
Linting on files with syntax errors

### ISSUE THREAD

**Issue by ostreifel** [tsqllint/tsqllint-vscode-extension#1]
I noticed that if even one line of the file has a syntax error the whole file will be ommitted from linting checks.

**Comment by dougwilson** [comment]
I believe this is the same behavior as other linters like eslint for javascript. If the parser is unable to parse the file, I'm not sure how it would be able tk lint it. Any thoughts on a possible solution?

**Comment by ostreifel** [comment]
Currently [the visitor](https://github.com/ostreifel/tsqllint/blob/master/TSQLLint.Lib/Parser/SqlRuleVisitor.cs#L37) checks for errors but I think it should just check if the fragment is not null.


```c#
namespace TSQLLint.Tests.UnitTests.Parser
{
    using System.IO;
    using NUnit.Framework;
    using TSQLLint.Lib.Parser;

    [TestFixture]
    public class FragmentBuilderTests
    {
        [Test]
        public void TestError()
        {
            var file = new StringReader(@"
                CREATE PROCEDURE proc1
                    ,@param1 NVARCHAR(someConst) = null;
                AS
                return 0;
");
            var builder = new FragmentBuilder();
            var fragment = builder.GetFragment(file, out var errors);
            Assert.AreNotEqual(0, errors.Count);
            Assert.NotNull(fragment);
        }
    }
}
```

**Comment by dougwilson** [comment]
Oh, I see, you're saying it would br some kind of change to the C# lib, not the extension, haha. I was super confused. So the repo and code for the lib is https://github.com/tsqllint/tsqllint if you want to open an issue (but a PR is even more ideal) :+1:

**Comment by ostreifel** [comment]
Ok thanks, will do
