### ISSUE TITLE
does support sql server compatibility 140 ?

### ISSUE THREAD

**Issue by ricoisme** [tsqllint/tsqllint-vscode-extension#20]
hi

I got some problem of analysis in VS code(v1.23.1).
such as semicolon-termination and create or alter proc not work.

thanks

**Comment by nathan-boyd** [comment]
Recent version of the [command line tool](https://github.com/tsqllint/tsqllint) have configurable compatibility level, but the version pinned in this extension does not. Its a simple fix, I'll spend some time on it today.

**Comment by nathan-boyd** [comment]
Published a new version of the extension v1.2.0 has been updated to the latest TSQLLint version, which has configurable compatibility levels. Just update your VSCode Extension and make sure you have a `.tsqllintrc` in your home directory, that contains at least the following: 

```json
{
    "compatability-level": 140
}

```

for more information about the base tool, and other configurations checkout the [TSQLLint docs](https://github.com/tsqllint/tsqllint#sql-compatibility-level)

**Comment by ricoisme** [comment]
so cool , thanks
